### ISSUE TITLE
submit a domain with http raises error

### ISSUE THREAD

**Issue by coderhs** [partheey/alexa_scrape#3]
When we submit a domain with an http, eg: https://redpanthers.co, its raises an error.

**Comment by partheey** [comment]
@coderhs It accpets url in the this format - 'www.redpanthers.co'. Since the validation for URL is not completed, It raises an error. I'll fix it up in next PR.

**Comment by partheey** [comment]
@coderhs Now it accepts domain address in the below format.
(https or http)://domain_name.(com, net, in, ..) => http://redpanthers.co
This issue has been fixed. So closing this.
